export const activitiesTypes = {
  bicycling: 'cardio',
  'circuit training': 'cardio',
  'resistance (weight) training': 'strength',
  'rope skipping': 'cardio',
  stretching: 'other',
  pilates: 'cardio',
  'water aerobics': 'cardio',
  'hatha yoga': 'other',
  'power yoga': 'other',
  ballet: 'other',
  aerobics: 'cardio',
  dancing: 'other',
  'cleaning (home)': 'other',
  cooking: 'other',
  laundry: 'other',
  'playing with children': 'other',
  'child care': 'other',
  'dog walking': 'other',
  lying: 'other',
  sitting: 'other',
  gardening: 'other',
  jogging: 'cardio',
  'running: 8 km/h': 'cardio',
  'running: 10 km/h': 'cardio',
  'running: 15 km/h': 'cardio',
  badminton: 'other',
  basketball: 'other',
  billiards: 'other',
  bowling: 'other',
  golf: 'other',
  gymnastics: 'cardio',
  'hacky sack': 'other',
  'martial arts': 'other',
  'rock climbing': 'other',
  skateboarding: 'other',
  rollerskating: 'other',
  soccer: 'other',
  'tai chi': 'other',
  tennis: 'other',
  volleyball: 'other',
  'backpacking / hiking': 'cardio',
  'walking - light pace, < 5 km/h': 'cardio',
  'walking - moderate pace, 5 km/h': 'cardio',
  'walking - fast pace, > 5 km/h': 'cardio',
  canoeing: 'cardio',
  kayaking: 'cardio',
  'swimming, light/moderate': 'cardio',
  'swimming, vigorous effort': 'cardio',
  'ice skating': 'other',
  skiing: 'other',
  'sexual activity': 'other',
  coding: 'other',
  'soft skills session': 'other'
};
