// encapsulate here createactivity

import { getSortedKeys, objectContainsKey } from '../utils/utils';

export const activitiesMET = {
  bicycling: 7.5,
  'circuit training': 6,
  'resistance (weight) training': 4,
  'rope skipping': 12,
  stretching: 2.3,
  pilates: 3,
  'water aerobics': 5,
  'hatha yoga': 2.5,
  'power yoga': 4,
  ballet: 5,
  aerobics: 7,
  dancing: 7.8,
  'cleaning (home)': 4,
  cooking: 3,
  laundry: 4,
  'playing with children': 3,
  'child care': 2.5,
  'dog walking': 3,
  lying: 1,
  sitting: 1.5,
  gardening: 3.5,
  jogging: 7,
  'running: 8 km/h': 8.3,
  'running: 10 km/h': 10.3,
  'running: 15 km/h': 13,
  badminton: 5.5,
  basketball: 6.5,
  billiards: 2.5,
  bowling: 3,
  golf: 4.8,
  gymnastics: 3.8,
  'hacky sack': 4,
  'martial arts': 10,
  'rock climbing': 7.5,
  skateboarding: 5,
  rollerskating: 7,
  soccer: 8,
  'tai chi': 3,
  tennis: 7.3,
  volleyball: 5,
  'backpacking / hiking': 7.8,
  'walking - light pace, < 5 km/h': 3,
  'walking - moderate pace, 5 km/h': 3.5,
  'walking - fast pace, > 5 km/h': 5,
  canoeing: 5,
  kayaking: 5,
  'swimming, light/moderate': 6,
  'swimming, vigorous effort': 9.8,
  'ice skating': 7,
  skiing: 7,
  'sexual activity': 2,
  coding: 28,
  'soft skills session': 48
};

export const sortedActivities = getSortedKeys(activitiesMET);
export const isActivityInList = (activity) => objectContainsKey(activitiesMET, activity);
